### ISSUE TITLE
Mock up health-status screen

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-ui#26]
Figma:
https://www.figma.com/file/8CiUNS9zH2NUm74VEicn64/Unity-screen-flows?type=design&node-id=2098%3A6287&mode=design&t=rgYJcTtn4jFHHLXh-1

- show list of services that are installed
- for each, show status (good / bad / warn?)
- for each, have a link to a web view if applicable
- for each, have a link to an endpoint if applicable

**Comment by mike-gangl** [comment]
initially, we won't have the links to the services/webview as of right now, i think we should remove that from the AC.

**Comment by rtapella** [comment]
https://www.figma.com/file/8CiUNS9zH2NUm74VEicn64/Unity-screen-flows?type=design&node-id=2098%3A6287&mode=design&t=rgYJcTtn4jFHHLXh-1

**Comment by rtapella** [comment]
@mike-gangl the landing-page links are in now, correct?

**Comment by rtapella** [comment]
![Image](https://github.com/unity-sds/unity-ui/assets/1156193/fe03f003-6107-4a05-ad56-376f9be066b2)

**Comment by mike-gangl** [comment]
Can we remove kion? in a perfect world, users won't _need_ access to that as they'll have unity accounts, not AWS accounts.

**Comment by mike-gangl** [comment]
Also, might be worth sorting by health status- unhealthy services pushed to the top for attention? Maybe color coded (red? what else?)

**Comment by rtapella** [comment]
That is just a mockup so I was trying to think of everything that could possibly go there. For now if we're driving the list off the health list, the navbar will include everything.

And yes you can sort/filter on any column and we could default to health status as the sort-order.

**Comment by rtapella** [comment]
![Health Dashboard 2](https://github.com/unity-sds/unity-ui/assets/1156193/fc72bb41-a638-40e0-af52-b51f255b01ee)

**Comment by rtapella** [comment]
Some sort of icon or color-tag may help scan the list, yes.

I prefer using a colored icon because it avoids issues with foreground/background contrast of the letters, and helps with color blindness by using shape as an additional communication method.

In this case I right-aligned it so the text is still in a column but it's probably better to left-align the icon in the health column and still keep the text left-aligned (it's just time-consuming to fix the mockup components to do this cleanly, so I stuck it on the right. it's easier in code :p )

**Comment by rtapella** [comment]
(to be clear: removing/adding kion or any other thing will depend on the contents of the health json response. the UI won't have any business logic to choose how to organize/filter the services/links )

**Comment by rtapella** [comment]
(Which, I just realized, means the health dashboard itself needs to be in that response unless we hard-code it)

**Comment by rtapella** [comment]
done
