### ISSUE TITLE
Get navbar into the Marketplace (needs httpd)

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-ui#30]
Depends on:
- https://github.com/unity-sds/unity-cs/issues/315
- https://github.com/unity-sds/unity-cs/issues/354
- https://github.com/unity-sds/unity-cs/issues/355

**Comment by rtapella** [comment]
httpd blocks:
- get navbar into marketplace
- navbar function once in marketplace

**Comment by rtapella** [comment]
unblocked as of May 20

**Comment by GodwinShen** [comment]
@anilnatha ping for status.

**Comment by rtapella** [comment]
@anilnatha : " @mike-gangl I have one question regarding the conf tile template for the proxy pass. Is it an accurate statement to say that the ALB URL that's used for the ProxyPass and ProxyPassReverse settings should be dynamically set when the terraform code is executed? The sample terraform code I've seen in other repos and in the unity-proxy documentation sorta implies that this value is hard-coded which doesn't feel right to me."

**Comment by rtapella** [comment]
re: terraform for ui: "the code Tom provided for us on the UI side I don't think is going to work properly because it's missing some key configurations, like handling auto scaling for the ECS target group. @anilnatha will fix it and wrap this up this week or next"

**Comment by rtapella** [comment]
@mike-gangl : "the terraform sets up the ALB + application, and can inspect the ALB it just set up for the url, then uses that value in the creation of a proxy route"

**Comment by rtapella** [comment]
hoping to close this on june 4 during "hackathon" team meeting

**Comment by galenatjpl** [comment]
@mike-gangl @anilnatha lets discuss this week in PI planning, what we should do with this ticket.

**Comment by rtapella** [comment]
remainder of this work will be captured in https://github.com/unity-sds/unity-sds-portal/issues/9
