### ISSUE TITLE
[New Feature]: Landing page shouldn't be blank

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ui#9]
Per @LucaCinquini : I suggest that the Home page is not completely blank - either expose the same links as in the menu, or at least some verbiage to provide context and don't give the first impression it's not working.

I agree, it should have some information about the system or the venue itself.

**Comment by rtapella** [comment]
We should also clean up the navigation menu so it doesn’t have stuff that you can’t navigate to, at least in the SIPS Test environment

**Comment by rtapella** [comment]
Maybe landing page is the Starting Line thing. could be common service page.

**Comment by rtapella** [comment]
Punting to 24.2

**Comment by rtapella** [comment]
perhaps near-term we could make the health-status board a “blank state” page. With links to each service/app along with the health status

**Comment by rtapella** [comment]
estimate based on making the health-page the default "Home" page if you log in with no other target UI

**Comment by rtapella** [comment]
new card-based entry point
